### ISSUE TITLE
What is localBasePaths designed for in CatalogApi?

### ISSUE THREAD

**Issue by Solodye** [criteo/criteo-api-java-sdk#14]
https://github.com/criteo/criteo-api-java-sdk/blob/3400c5bb4d0a636e5a2210e6bd8b4611a8023e9c/sdks/marketingsolutions_preview/src/main/java/com/criteo/api/marketingsolutions/preview/api/CatalogApi.java#L102

localBasePaths will be always empty, then line 108 cannot be reached.
https://github.com/criteo/criteo-api-java-sdk/blob/3400c5bb4d0a636e5a2210e6bd8b4611a8023e9c/sdks/marketingsolutions_preview/src/main/java/com/criteo/api/marketingsolutions/preview/api/CatalogApi.java#L108

**Comment by gturri** [comment]
FTR: the code is this repo is auto-generated by https://github.com/criteo/criteo-api-sdk-generator ; which itself relies on [OpenApiGenerator](https://openapi-generator.tech/).

`localBasePaths` is hence part of the code generated by openApiGenerator ([this one](https://github.com/OpenAPITools/openapi-generator/blob/v6.3.0/modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api.mustache#L124).
I'm not too sure why openApiGenerator has this (ie: in which cases it's supposed to be useful), but all that matters for us is the url `https://api.criteo.com` which appears as the `basePath` [here](https://github.com/criteo/criteo-api-java-sdk/blob/3400c5bb4d0a636e5a2210e6bd8b4611a8023e9c/sdks/marketingsolutions_preview/src/main/java/com/criteo/api/marketingsolutions/preview/ApiClient.java#L68)

I'll close that issue because it seems there is nothing to be done with this, but feel free to re-open it if you have a different opinion.
